# Generated by Django 4.2.7 on 2023-12-28 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNICl', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Teléfono', models.PositiveIntegerField()),
                ('Nombre', models.CharField(max_length=40)),
                ('Correo', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Director', models.CharField(max_length=80)),
                ('Pais', models.CharField(max_length=50)),
                ('Genero', models.CharField(choices=[('Terror', 'Terror'), ('Comedia', 'Comedia'), ('Acción', 'Acción')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('NombreDep', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('Codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Autor', models.CharField(max_length=50)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Titulo', models.CharField(max_length=100, null=True)),
                ('FechaCont', models.DateField(null=True)),
                ('DNIT', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('Codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Autor', models.CharField(max_length=50)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('DatosSuscripcion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual')], default='Mensual', max_length=10)),
                ('Nivel', models.CharField(choices=[('Estandar', 'Estandar'), ('Premium', 'Premium')], default='Estandar', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('DNIT', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=40)),
                ('Teléfono', models.CharField(max_length=9)),
                ('CorreoElectronico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('Titulo', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Duracion', models.IntegerField()),
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('Titulo', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Temporadas', models.IntegerField()),
                ('contenido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('DNIT', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NombreDep', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Obtiene',
            fields=[
                ('DatosSuscripcion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('DNICl', models.CharField(max_length=9, unique=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='GastoContenido',
            fields=[
                ('Codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contenido')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gasto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.CheckConstraint(check=models.Q(('Genero__in', ['Terror', 'Comedia', 'Acción'])), name='valid_genre'),
        ),
        migrations.AddConstraint(
            model_name='contenido',
            constraint=models.UniqueConstraint(fields=('Titulo', 'Fecha'), name='unique_contenido'),
        ),
        migrations.AddConstraint(
            model_name='serie',
            constraint=models.UniqueConstraint(fields=('Titulo', 'Fecha'), name='unique_serie'),
        ),
        migrations.AddConstraint(
            model_name='pelicula',
            constraint=models.UniqueConstraint(fields=('Titulo', 'Fecha'), name='unique_pelicula'),
        ),
    ]
