# Generated by Django 4.2.7 on 2024-01-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gasto_dnit_gasto_fechacont_gasto_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='Nivel',
        ),
    ]
