# Generated by Django 4.2.7 on 2024-01-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_suscripcion_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteObtiene',
            fields=[
                ('DNICl', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=30)),
                ('datos_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion')),
            ],
            options={
                'db_table': 'Cliente-Obtiene',
            },
        ),
        migrations.RemoveField(
            model_name='obtiene',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='obtiene',
            name='suscripcion',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Obtiene',
        ),
    ]
