# Generated by Django 4.2.7 on 2024-01-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_clienteobtiene_remove_obtiene_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incluye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Estandar', 'Estandar'), ('Premium', 'Premium')], max_length=50)),
                ('datos_suscripcion', models.ForeignKey(db_column='DatosSuscripción', on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion')),
                ('fecha', models.ForeignKey(db_column='Fecha', on_delete=django.db.models.deletion.CASCADE, related_name='incluye_fechas', to='app.contenido')),
                ('titulo', models.ForeignKey(db_column='Titulo', on_delete=django.db.models.deletion.CASCADE, related_name='incluye_titulos', to='app.contenido')),
            ],
            options={
                'db_table': 'Incluye',
                'unique_together': {('titulo', 'fecha', 'datos_suscripcion')},
            },
        ),
    ]
