# Generated by Django 4.2.7 on 2024-01-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_incluye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incluye',
            name='nivel',
        ),
    ]
