# Generated by Django 4.2.7 on 2024-01-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_gastocontenidosalario_fecha_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastocontenidosalario',
            old_name='contenido',
            new_name='Contenido',
        ),
    ]
