# Generated by Django 4.2.7 on 2024-01-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_contenido_gastocontenidosalario_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorPertenece',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=40)),
                ('Telefono', models.CharField(max_length=9)),
                ('CorreoElectronico', models.EmailField(max_length=50)),
                ('NombreDep', models.ForeignKey(db_column='NombreDep', on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Pertenece',
        ),
        migrations.AlterField(
            model_name='gastocontenidosalario',
            name='DNIT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trabajadorpertenece'),
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
