# Generated by Django 4.2.7 on 2024-01-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_trabajadorpertenece_delete_pertenece_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadorpertenece',
            old_name='DNI',
            new_name='DNIT',
        ),
    ]
